name = "cloudflare-cache-monitor-worker"
main = "src/index.js"
compatibility_date = "2024-09-21"

account_id = "5e69ab0bb67aab3c155101196a0bb418"
workers_dev = true

[vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1135511303713210368/UnSTLY3P77V23xT-KXwyCj4bGglLAbVDyLV3d0Z-LuTiGZ7dbmj2m7LbM-w-wkajaGeA"
DISCORD_EMBED_FOOTER_LABEL = "Jogajunto Cloudflare cache monitor"
DISCORD_EMBED_FOOTER_ICON_URL = "https://jogajunto.co/apple-touch-icon.png"